yarnPath: .yarn/releases/yarn-3.3.1.cjs
nodeLinker: pnp
  
packageExtensions:
    'eslint-config-react-app@* ':
      dependencies:
        '@babel/plugin-syntax-flow': '*'
        '@babel/plugin-transform-react-jsx': '*'
    '@craco/craco@* ':
      dependencies:
        'ts-node': "*"
        '@types/node': "*"
        'postcss': '*'
        'typescript': '*'

